### PR TITLE
Made some changes to ChangeGameStateCodec.

### PR DESCRIPTION
**Pull request by gorillago**

### CODE REVIEW

**Comment by geret13** [comment]
If we look at [wiki.vg](http://wiki.vg/Protocol#Change_Game_State) we can see that there is a id gap between `(8) Fade time` and `(10) Play mob appearance`. Please add something like a dummy value or move the ids to a field to fill up that space.

**Comment by geret13** [comment]
Also, the value is a float. Not a double.

**Comment by gorillago** [comment]
I thought we were using doubles instead of floats?

**Comment by geret13** [comment]
Yes, but the codec has to stay true to the protocol

**Pull request merged**
